<?php
// $Id:$
/*
  By RoopleTheme
  jQuery drop-down menus with animation and UI enhancments.
 */

/**
 * Implementation of hook_help().
 */
function superfish_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/settings/modules#description':
      $output .= t('Drop-down menus with javascript enhancments.');
      break;
    case 'admin/settings/superfish':
      $output .= t('<p>This module uses the superfish jquery plugin in order to provide a javascript-enabled drop-down menu. Additional features can be provided by the easing, hoverIntent, supersubs, and bgiframe plugins. Configure the menu block at !link</p>', array('!link' => l('admin/build/block', 'admin/build/block')));
      break;
  }
  return $output;
}

/**
 * Implementation of hook_form_alter().
 */
function superfish_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'system_theme_settings':

      // This is a global setting, so only insert the field 
      // on the global settings page.
      if (arg(4)) {
        return;
      }

      // Have to add a custom submit handler since this form doesn't use 
      // the standard system submit handler.
      $form['#submit'][] = 'superfish_system_theme_settings_submit';

      // Add global theme setting for a custom CSS file.
      $form['superfish_custom_css'] = array(
        '#type' => 'textfield',
        '#title' => t('Path to custom Superfish Menus CSS file'),
        '#description' => t('To override the default Superfish Menus CSS layout, enter the path to your custom CSS file.  It should be a relative path from the root of your Drupal install (e.g. sites/all/themes/example/mymenu.css).'),
        '#default_value' => variable_get('superfish_custom_css', ''),
        // Field appears below submit buttons without this -- yucky.
        '#weight' => 0,
      );
      break;
  }
}

/**
 * Records the superfish menu custom CSS file per theme.
 */
function superfish_system_theme_settings_submit($form, &$form_state) {
  variable_set('superfish_custom_css', $form_state['values']['superfish_custom_css']);
}

/**
 * Implemention of hook_menu().
 */
function superfish_menu() {
  $items['admin/settings/superfish'] = array(
    'title' => 'Superfish Menus',
    'description' => 'Configure Superfish Menus.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('superfish_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}


/**
 * Settings form as implemented by hook_menu
 */
function superfish_admin_settings() {
  $form['superfish_number'] = array(
    '#type' => 'textfield',
    '#description' => t('The total number of independent Superfish menus blocks you want. Enter a number between 0 and 99. If you set this to 0, you will have no blocks created but you can still use the Superfish menus theme functions directly in your theme.'),
    '#default_value' => variable_get('superfish_number', '2'),
    '#size' => 2,
  );

  $navtype = variable_get('superfish_navtype',  0);
  $animation = variable_get('superfish_animation',  0);
  $speed = variable_get('superfish_speed',  1);
  $easing = variable_get('superfish_easing',  0);

  $form['superfish_delay'] = array(
    '#type' => 'select',
    '#title' => t('Mouseout Delay, in Milliseconds'),
    '#description' => t('Mouseout Delay, in Milliseconds.'),
    '#default_value' => variable_get('superfish_delay', 800),
    '#options' => drupal_map_assoc(array(0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000)),
  );

  $form['superfish_navtype'] = array(
    '#type' => 'select',
    '#title' => t('Superfish Menu Type'),
    '#description' => t("Superfish Menu Type."),
    '#options' => array('Standard', 'Navbar', 'Vertical'),
    '#default_value' => $navtype,
  );

  $form['superfish_animation'] = array(
    '#type' => 'select',
    '#title' => t('Animation Method'),
    '#description' => t("Animation Method."),
    '#options' => array('Fade In', 'Slide Down', 'Slide Right', 'Slide Both', 'Fade In Slide Down', 'Fade In Slide Right', 'Fade In Slide Both'),
    '#default_value' => $animation,
  );

  $form['superfish_speed'] = array(
    '#type' => 'select',
    '#title' => t('Animation Speed'),
    '#description' => t("Animation Speed."),
    '#options' => array('slow', 'normal', 'fast'),
    '#default_value' => $speed,
  );

  $form['superfish_easing'] = array(
    '#type' => 'select',
    '#title' => t('Easing Method'),
    '#description' => t("Easing Method."),
    '#options' => array('linear', 'swing', 'easeOutQuad', 'easeOutCubic' ,'easeOutQuart', 'easeOutQuint', 'easeOutSine', 'easeOutExpo', 'easeOutCirc', 'easeOutBounce', 'easeOutBack', 'easeOutElastic'),
    '#default_value' => $easing,
  );

  $form['superfish_dropshadow'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable Drop Shadow'),
    '#default_value' => variable_get('superfish_dropshadow', 0),
  );

  $form['superfish_autoarrows'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable Auto Arrows'),
    '#default_value' => variable_get('superfish_autoarrows', 0),
  );

  $form['superfish_hoverintent'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable HoverIntent Plugin'),
    '#default_value' => variable_get('superfish_hoverintent', 1),
  );

  $form['superfish_supersubs'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable Supersubs Plugin'),
    '#default_value' => variable_get('superfish_supersubs', 1),
  );

  $form['superfish_bgiframe'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable Bglframe Plugin'),
    '#default_value' => variable_get('superfish_bgiframe', 1),
  );

  // Custom validation to make sure the user is entering numbers.
  $form['#validate'][] = 'superfish_settings_validate';
  
  return system_settings_form($form);
}

/**
 * Custom validation for the settings form.
 **/
function superfish_settings_validate($form, &$form_state) {
  $number = $form_state['values']['superfish_number'];
  // Check to make sure it is a number and that is a maximum of 2 digits.
  if (!is_numeric($number) || strlen($number) > 2) {
      form_set_error('superfish_number', t('You must enter a number from 0 to 99.'));
  }
}

/**
 * Implementation of hook_block().
 */
function superfish_block($op = 'list', $delta = 0, $edit = array()) {
  global $user;

  switch ($op) {
    case 'list':
      for ($i = 1; $i <= variable_get('superfish_number', '2'); $i++) {
        $blocks[$i]['info'] = variable_get('superfish_name_'. $i, 'Nice Menu '. $i) .' (Nice Menu)';
      }
      return $blocks;
    break;

    case 'configure':
      $form['superfish_name_'. $delta] = array(
        '#type' => 'textfield',
        '#title' => t('Menu Name'),
        '#default_value' => variable_get('superfish_name_'. $delta, 'Nice Menu '. $delta),
      );
      $form['superfish_menu_'. $delta] = array(
        '#type' => 'select',
        '#title' => t('Source Menu Tree'),
        '#description' => t('The menu tree from which to show a superfish menu.'),
        '#default_value' => variable_get('superfish_menu_'. $delta, 'navigation:0'),
        '#options' => menu_parent_options(menu_get_menus(), 0),
      );
      $form['superfish_type_'. $delta] = array(
        '#type' => 'select',
        '#title' => t('Menu Style'),
        '#description' => t('right: menu items are listed on top of each other and expand to the right') .'<br />'. t('left: menu items are listed on top of each other and expand to the left') .'<br />'. t('down: menu items are listed side by side and expand down'),
        '#default_value' => variable_get('superfish_type_'. $delta, 'right'),
        '#options' => drupal_map_assoc(array('right', 'left', 'down')),
      );
      return $form;
    break;

    case 'save':
      variable_set('superfish_name_'. $delta, $edit['superfish_name_'. $delta]);
      variable_set('superfish_menu_'. $delta, $edit['superfish_menu_'. $delta]);
      variable_set('superfish_type_'. $delta, $edit['superfish_type_'. $delta]);
    break;

    case 'view':
      // Build the superfish menu for the block.
      list($menu_name, $mlid) = explode(':', variable_get('superfish_menu_'. $delta, 'navigation:0'));
      $direction = variable_get('superfish_type_'. $delta, 'right');
      if ($output = theme('superfish_menu', $delta, $menu_name, $mlid, $direction)) {
        $block['content'] = $output['content'];
        if (variable_get('superfish_type_'. $delta, 'right') == 'down') {
          $class = 'superfish-menu-hide-title';
        }
        else {
          $class = 'superfish-menu-show-title';
        }
        // If we're building the navigation block
        // use the same block title logic as menu module.
        if ($output['subject'] == t('navigation') && $user->uid) {
          $subject = $user->name;
        }
        else {
          $subject = $output['subject'];
        }
        $block['subject'] = '<span class="'. $class .'">'. check_plain($subject) .'</span>';
      }
      else {
        $block['content'] = false;
      }
      return $block;
    break;
  }
}

/**
 * Implmentation of hook_theme().
 **/
function superfish_theme() {
  return array(
    'superfish_menu_tree' => array(
      'arguments' => array('menu_name' => NULL, 'mlid' => NULL, 'menu' => NULL),
    ),
    'superfish_menu_build' => array(
      'arguments' => array('menu' => NULL),
    ),
    'superfish_menu' => array(
      'arguments' => array('id' => NULL, 'menu_name' => NULL, 'mlid' => NULL, 'direction' => 'right', 'menu' => NULL),
    ),
    'superfish_menu_primary_links' => array(
      'arguments' => array('direction' => 'down', 'menu' => NULL),
    ),
    'superfish_menu' => array(
      'arguments' => array('id' => NULL, 'pid' => NULL, 'direction' => 'right', 'menu' => NULL),
    ),
    'superfish_menu_primary_links' => array(
      'arguments' => array('direction' => 'down', 'menu' => NULL),
    ),
  );
}

function _superfish_getjsinit() {

  $delay = variable_get('superfish_delay',  800);

	if (isset($_COOKIE["superfishtype"])) {
		$navtype = intval($_COOKIE["superfishtype"]);
	} 
	else {
		$navtype = variable_get('superfish_navtype',  0);
	}

  if (isset($_COOKIE["superfishspeed"])) {
    $speed = intval($_COOKIE["superfishspeed"]);
  } 
  else {
    $speed = variable_get('superfish_speed',  1);
  }
  $speed_choices = array('slow', 'normal', 'fast');
  $speed_string = $speed_choices[$speed];

  if (isset($_COOKIE["superfishease"])) {
    $easing = intval($_COOKIE["superfishease"]);
  } 
  else {
    $easing = variable_get('superfish_easing',  0);
  }
  $easing_choices = array('', 'jswing', 'easeOutQuad', 'easeOutCubic', 'easeOutQuart', 'easeOutQuint', 'easeOutSine', 'easeOutExpo', 'easeOutCirc', 'easeOutBounce', 'easeOutBack', 'easeOutElastic');
  $easing_string = $easing_choices[$easing];
  if ($easing_string != '') {
    $easing_js = "jQuery.easing.def = '". $easing_string ."';";
  } 
  else {
    $easing_js = '';
  }

  if (isset($_COOKIE["superfishfx"])) {
    $animation = intval($_COOKIE["superfishfx"]);
  } 
  else {
    $animation = variable_get('superfish_animation',  0);
  }
  $animation_choices = array("opacity:'show'", "height:'show'", "width:'show'", "height:'show',width:'show'", "opacity:'show',height:'show'", "opacity:'show',width:'show'", "opacity:'show',height:'show',width:'show'");
  $animation_string = $animation_choices[$animation];

  if (variable_get('superfish_dropshadow', 0)) {
    $dropshadow = 'true';
  }
  else {
    $dropshadow = 'false';
  }
  
  if (variable_get('superfish_autoarrows', 0)) {
    $autoarrows = 'true';
  }
  else {
    $autoarrows = 'false';
  }
  
  if (variable_get('superfish_hoverintent', 1)) {
    $disablehoverintent = 'false';
  }
  else {
    $disablehoverintent = 'true';
  }
  
  if (variable_get('superfish_bgiframe', 1)) {
    $bgiframe = ".find('ul').bgIframe({opacity:false})";
  }
  else {
    $bgiframe = '';
  }
  
  if ((variable_get('superfish_supersubs', 1)) && $navtype == 0) {
    $supersubs = ".supersubs({minWidth: 12, maxWidth: 30, extraWidth: 1})";
  }
  else {
    $supersubs = '';
  }
  
  return ($easing_js ."jQuery(function(){
        jQuery('ul.sf-menu')". $supersubs .".superfish({delay: ". $delay .", animation: {". $animation_string ."}, speed: '".  $speed_string ."',
              autoArrows: ". $autoarrows .", dropShadows: ". $dropshadow .", disableHI: ". $disablehoverintent .", pathClass:  'active'})". $bgiframe .";
    });  ");
}

/**
 * Implementation of hook_init().
 *
 * We are adding the JavaScript and CSS here rather than theme_superfish_menu
 * because when block caching is enabled none of it would get fired
 * and the menus are unstyled.
 **/
function superfish_init() {
    drupal_add_css(drupal_get_path('module', 'superfish') .'/css/superfish.css');

    if (isset($_COOKIE["superfishtype"])) {
      $navtype = intval($_COOKIE["superfishtype"]);
    } 
    else {
      $navtype = variable_get('superfish_navtype',  0);
    }
    if ($navtype == 1) {
      drupal_add_css(drupal_get_path('module', 'superfish') .'/css/superfish-navbar.css');
    }

    if (variable_get('superfish_hoverintent', 1)) {
      drupal_add_js(drupal_get_path('module', 'superfish') .'/js/hoverIntent.js');
    }

    if (variable_get('superfish_bgiframe', 1)) {
      drupal_add_js(drupal_get_path('module', 'superfish') .'/js/jquery.bgiframe.min.js');
    }

    drupal_add_js(drupal_get_path('module', 'superfish') .'/js/superfish.js');

    if ((variable_get('superfish_supersubs', 1)) && $navtype == 0) {
      drupal_add_js(drupal_get_path('module', 'superfish') .'/js/supersubs.js');
    }

    if (!variable_get('superfish_dropshadow', 0)) {
      drupal_set_html_head('<style type="text/css">.block ul.sf-menu ul { padding: 0 0 0 0; }</style>');
    }

//    if (variable_get('superfish_easing', 0)) {
      drupal_add_js(drupal_get_path('module', 'superfish') .'/js/jquery.easing.1.3.js');
//    }

    drupal_add_js(_superfish_getjsinit(), "inline");
}

/**
 * Builds the final superfish menu.
 *
 * @param $menu_name
 *   The top-level menu name that contains the menu to use (e.g. navigation 
 *   or primary-links) for Drupal menus. For custom $menus this is just the 
 *   name for menu display.
 * @param $mlid
 *   The menu ID from which to start building the items, i.e. the parent
 *   of the displayed menu.
 * @param $menu
 *   Optional. A custom menu array to use for theming -- it should have
 *   the same structure as that returned by menu_tree_all_data().
 * @return
 *   An HTML string of properly nested superfish menu lists.
 */
function theme_superfish_menu_tree($menu_name, $mlid = NULL, $menu = NULL) {
  // Load the full menu array.
  $menu = isset($menu) ? $menu : menu_tree_all_data($menu_name);
  
  // For custom $menus and menus built all the way from the top-level we
  // don't need to "create" the specific sub-menu and we need to get the title
  // from the $menu_name since there is no "parent item" array.
   
  // Create the specific menu if we have a mlid.
  if (!empty($mlid)) {
    // Load the parent menu item.
    $item = menu_link_load($mlid);
    $title = $item['title'];
    // Narrow down the full menu to the specific sub-tree we need.
    for ($p = 1; $p < 10; $p++) {
      if ($sub_mlid = $item["p$p"]) {
        $subitem = menu_link_load($sub_mlid);
        // Menu sets these ghetto-ass keys in _menu_tree_check_access().
        $menu = $menu[(50000 + $subitem['weight']) .' '. $subitem['title'] .' '. $subitem['mlid']]['below'];
      }
    }
  }
  // Otherwise just set a title and move on.
  else {
    $title = $menu_name;
  }
  
  $output['content'] = '';
  $output['subject'] = $title;

  if ($menu) {
    $output['content'] .= theme('superfish_menu_build', $menu);
  }

  return $output;
}

/**
 * Helper function that builds the nested lists of a superfish menu.
 *
 * @param $menu
 *   Menu array from which to build the nested lists. 
 */
function theme_superfish_menu_build($menu) {
  $output = '';  

  foreach ($menu as $menu_item) {
    $mlid = $menu_item['link']['mlid'];
    // Check to see if it is a visible menu item.
    if ($menu_item['link']['hidden'] == 0) {
      // Build class name based on menu path 
      // e.g. to give each menu item individual style.
      // Strip funny symbols.
      $clean_path = str_replace(array('http://', '<', '>', '&', '=', '?', ':'), '', $menu_item['link']['href']);
      // Convert slashes to dashes.
      $clean_path = str_replace('/', '-', $clean_path);
      $path_class = 'menu-path-'. $clean_path;
      // If it has children build a nice little tree under it.
      if ((!empty($menu_item['link']['has_children'])) && (!empty($menu_item['below']))) {
        // Keep passing children into the function 'til we get them all.
        $children = theme('superfish_menu_build', $menu_item['below']);
        // Set the class to parent only of children are displayed.
        $parent_class = $children ? 'menuparent ' : '';
        $output .= '<li id="menu-'. $mlid .'" class="'. $parent_class . $path_class .'">'. theme('menu_item_link', $menu_item['link']);       
        // Build the child UL only if children are displayed for the user.
        if ($children) {
          $output .= '<ul>';
          $output .= $children;                     
          $output .= "</ul>\n";
        }
        $output .= "</li>\n";
      }
      else {
        $output .= '<li id="menu-'. $mlid .'" class="'. $path_class .'">'. theme('menu_item_link', $menu_item['link']) .'</li>'."\n";
      }
    }
  }
  return $output;
}

/**
 * General theming function to allow any menu tree to be themed 
 * as a superfish menu.
 *
 * @param $id
 *   The superfish menu ID.
 * @param $menu_name
 *   The top parent menu name from which to build the full menu.
 * @param $mlid
 *   The menu ID from which to build the displayed menu.
 * @param $direction
 *   Optional. The direction the menu expands. Default is 'right'.
 * @param $menu
 *   Optional. A custom menu array to use for theming --
 *   it should have the same structure as that returned
 *  by menu_tree_all_data(). Default is the standard menu tree.
 * @return
 *   An HTML string of superfish menu links.
 */
function theme_superfish_menu($id, $menu_name, $mlid, $direction = 'right', $menu = NULL) {
  $output = array();

  if ($menu_tree = theme('superfish_menu_tree', $menu_name, $mlid, $menu)) {
    if ($menu_tree['content']) {
  $sfclass = 'sf-menu ';
  if (isset($_COOKIE["superfishtype"])) {
    $navtype = intval($_COOKIE["superfishtype"]);
  } 
  else {
    $navtype = variable_get('superfish_navtype',  0);
  }

  if ($navtype == 1) {
    $sfclass .= ' sf-navbar ';
  }
  $sfclass .= 'superfish-menu superfish-menu-'. $direction;

      $output['content'] = '<ul class="'. $sfclass .'" id="superfish-menu-'. $id .'">'. $menu_tree['content'] .'</ul>'."\n";
      $output['subject'] = $menu_tree['subject'];
    }
  }
  return $output;
}

/**
 * Theme primary links as superfish menus
 *
 * @param $direction
 *   Optional. The direction the menu expands. Default is 'down'.
 * @param $menu
 *   Optional. A custom menu array to use for theming --
 *   it should have the same structure as that returned
 *   by menu_tree_all_data(). Default is the standard menu tree.
 * @return
 *   An HTML string of superfish menu primary links.
 */
function theme_superfish_menu_primary_links($direction = 'down', $menu = NULL) {
  $menu_name = variable_get('menu_primary_links_source', 'primary-links');
  $output = theme('superfish_menu', 0, $menu_name, 0, $direction, $menu);
  return $output['content'];
}
